services:
  gateway:
    build:
      context: ./gateway_service
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - flaky_backend



  flaky_backend:
    build: ./flaky_service
    ports:
      - "8001:8001"
